const { MessageEmbed } = require("discord.js");

module.exports.run = async (Client, message, args) => {
    const ar = "<a:_util_arrow:864810269771300875>"

    const bag1 = new MessageEmbed()
        .setTitle("Bag Expansion (Collectibles)")
        .setURL("https://discord.com/invite/Sbp2nt8QHe")
        .setDescription(`${ar} 51: Colon Skin x1 **Colon** (Land Under Development)\n${ar} 52: Gorgeous Fur x1 **Lavarca** (Rakau Plains)\n${ar} 53: Spina 1.000\n${ar} 54: Minotaur Skin x1 **Minotaur** (Ruined Temple: Forbidden Hall)\n${ar} 54: Orange Crystal Fragment x1 **Cobre** (Icule Lake)\n${ar} 55: Forest Wolf Skin x1 **Forest Wolf** (Marbaro Forest: Deepest)\n${ar} 55: Goblin Medal x1 **Boss Goblin** (Ribisco Cave: Deepest Part)\n${ar} 56: Spina 2.000\n${ar} 57: Mochelo Fur x1 **Mochelo** (Fiery Vulcano A3)\n${ar} 57: Linen Cloth x10 **Crow Killer** (Douce Hamlet)\n${ar} 58: Green Dragon Fur x1 **Forestia** (Land of Chaos)\n${ar} 58: High Quality Horn x10 **Billy** (Yorl Highlands)\n${ar} 59: Boss Roga's Belt x1 **Boss Roga** (Saham Crater Cave: Deepest)\n${ar} 59: Broadcloth x10 **Orc Warrior** (Saham Crater Cave)\n${ar} 60: Spina 4.000`)
        .setImage("https://i.imgur.com/V0UhnF9.png")
        .setColor("#2f3136")

    const bag2 = new MessageEmbed()
        .setDescription(`${ar} 61: Sharp Bear Claw x2 **Violacoon** (Darkanon Plains)\n${ar} 61: Sheeting Fabric x20 **Cassy** (Ancient Empress Tomb)\n${ar} 62: Heavy Tough Chain x2 **Masked Warrior** (Cultivation)\n${ar} 62: Polyester Cloth x20 **Wandering Shadow** (Lost Town)\n${ar} 63: Grass Dragon Scale x2 **Grass Dragon Yelb** (Albatif Village)\n${ar} 64: Space Wolf Fur x20 **Outer World Wolf** (Road to another)\n${ar} 64: Spina 8.000\n${ar} 65: Torn Cloak x2 **Goovua** (Akaku Desert: Hill)\n${ar} 65: Squirrel Fur x20 **Rodentail** (Maia Diela)\n${ar} 66: Jade Raptor Fur x2 **Jade Raptor** (Gravel Terrace)\n${ar} 66: Goat Fur x20 **Koza** (Dunkel Valley)\n${ar} 67: Twilight Dragon Fur x2 **Twilight Dragon** (Fort Solfini: Roof)\n${ar} 67: Fleecy Fur **Rabby**/**Little Snow Boar** (Polde Ice Valley)\n${ar} 68: Spina 16.000\n${ar} 69: Chain of Purgatory x2 **Cerberus** (Spring of Rebirth: Top)\n${ar} 69: Wavering Cloth x20 **Jewel Eye** (Spring of Rebirth)\n${ar} 70: Aranea Silk x2 **Aranea** (Garden of Sublimation: Central Part)\n${ar} 70: Small Spider Silk x20 **Aramia** (Garden of Sublimation)`)
        .setImage("https://i.imgur.com/V0UhnF9.png")
        .setColor("#2f3136")
    
    const bag3 = new MessageEmbed()
        .setDescription(`${ar} 71: Copied Goddess's Cloth x3 **Imitacia** (Dark Castle: Grand Hall)\n${ar} 71: Floating Cloth x10 **Flying Executioner** (Cradle of Soldier)\n${ar} 71: Soft Paw x20 **Bunny Summoner** (Trace of Dark River)\n${ar} 72: Evil Beast Mane x3 **Memecoleus** (Dark Castle: Area 2)\n${ar} 72: Hard Paw Pad x10 **Memecoleus** (Dark Castle: Area 2)\n${ar} 72: Dark Shadow Feather x20 **Shadow Fly** (Dark Castle)\n${ar} 73: Spina 32.000\n${ar} 74: Tapir Fur ×3 **Tapir** (Blazing Garben: Surface)\n${ar} 74: Stiff Fur ×10 **Wooly** (Blazing Garben: Surface)\n${ar} 74: Anti-Rust Oil ×20 **Ornis Demi Machina** (Artillery Defense)\n${ar} 75: Ancient Fabric ×3 **Proto Leon** (Singalore Ruins: 3rd Floor)\n${ar} 75: Soft Tree Bark x10 **Floral Bee** (Site of Simcracker)\n${ar} 75: Dirty Potum Hair ×20 **Skum Potum** (Klaspe Slum)\n${ar} 76: Crimson Huge Bone ×3 **Dusk Machina** (Small Machina)\n${ar} 76: Torn Black Coat ×10 **Rugos Demi Machina** (Small Machina)\n${ar} 76: Torn Chain ×20 **Torture Machins** (Small Machina)\n${ar} 77: Chimera Scale ×3 **Mozto Machina** (Large Machina)\n${ar} 77: Mysterious Luminary ×10 **Horn Machina** (Large Machina)\n${ar} 77: Tough Tentacle ×20 **Ledon Machina** (Large Machina)\n${ar} 78: Spina 64.000\n${ar} 79: Forest Spirit's Robe ×3 **Lalvada** (Monster's Forest)\n${ar} 79: Planet Fang ×10 **Nepenthe** (Monster's Forest)\n${ar} 79: Felt Fabric ×20 **Puppet Dragon** (Lufenas Mansion: Entrance)\n${ar} 80: Lyark Alloy ×3 **Gwaimol** (Cuervo Jail: Roof)\n${ar} 80: Torn Officier Clothes ×10 **Lyark Jailer** (Cuervo Jail)\n${ar} 80: Ox Fabric ×20 **Lyark Specialist** (Brahe Laboratory)`)
        .setImage("https://i.imgur.com/V0UhnF9.png")
        .setColor("#2f3136")

    const bag4 = new MessageEmbed()
        .setDescription(`${ar} 81: Light Emitting Cloth ×4 **Seraph Machina** (Buried Tower)\n${ar} 81: Damaged Artificial Leather ×20 **Lyark Brawler** (Suburb)\n${ar} 81: Executer's Loincloth ×20 **Volo** (Suburb of Droma Square)\n${ar} 82: Lil Empress Cloth Piece ×4 **Venena Coenubia** (Throne)\n${ar} 82: Hard Armor Bit ×20 **High Tigris** (Ultimea Palace: Storage)\n${ar} 82: Snake Skin ×20 **8Pond Snake** (Copia Reservoir)\n${ar} 83: Spina 100.000\n${ar} 84: Mom Fluck Skin ×4 **Mom Fluck** (Forgotten Cave)\n${ar} 84: Colon Big Leaf ×20 **Leedle Colon** (Rokoko Plains)\n${ar} 84: Vertical Stripe Fur ×20 **Tehon** (Curonne Forest: East)\n${ar} 85: Mardula Spiritual Cloth ×4 **Mardula** (Hall of Blessings Gods)\n${ar} 85: Mysterious Shiny Cloth ×20 **Bubble Angel** (Shrine of Gods)\n${ar} 85: Grey Feather ×20 **Haliabubo** (Ruins of Mt. Mithurna)\n${ar} 86: Carbuncle Fur ×4 **Carbuncle** (Hall of Construction Gods)\n${ar} 86: Knit Fabric ×20 **Bubble Angel** (Hall of Construction Gods)\n${ar} 86: Bag Bear Tail ×20 **Oddy** (Hall of Construction Gods)\n${ar} 87: King Piton Fur ×4 **King Piton** (Elf Mountains: Shrine)\n${ar} 87: Thick White Fur ×20 **Billy** (Garden of Ice and Snow)\n${ar} 87: Stiff Grey Fur ×20 **Silveria** (Elf Mountains: Area 1/3)\n${ar} 88: Ancient Ingot ×4 **Thug Golem** (Dark Dragon Shrine: Middle)\n${ar} 88: Ice Wolf Fang ×20 **Corloup** (Elf Mountains: Area 1/2/3))\n${ar} 88: Dusky Fabric ×20 **Soul Reaper** (Dark Dragon Shrine)\n${ar} 89: Spina 200.000\n${ar} 90: Tuscog Fang ×4 **Tuscog** (Eryldan Street)\n${ar} 90: Larva Silk ×20 **Moss Mole** (Forest of Ein)\n${ar} 90: Werewolf Fur ×20 **Wolfret** (Eryldan Street: Area 2/3)`)
        .setImage("https://i.imgur.com/V0UhnF9.png")
        .setColor("#2f3136")

    const bag5 = new MessageEmbed()
        .setDescription(`${ar} 91: Kuzto Splinter ×5 **Kuzto** (Labilans Sector: Square)\n${ar} 91: Stoat Fur ×20 **Sentreast** (Fabriska Sector)\n${ar} 91: Mysterious Waist Sash ×30 **Moculus** (Fractum Sector: Area)\n${ar} 92: Crystal Pouch ×5 **Canemofish** (Recetacula Sector: Area 1)\n${ar} 92: Cushy Tail ×20 **Alpoca** (Dikkit Sector)\n${ar} 92: Sturdy Papula ×30 **Toxinaria** (Recetacula Sector: Area 1/2/3)\n${ar} 93: Repthon Wings ×5 **Rephton** (Deltzon Research Zone)\n${ar} 93: Legume Button ×20 **Marquis Coryn** (Old Lufenas Mansion)\n${ar} 93: Frock Coat Scrap ×30 **Swirly Whirly** (Deltzon Research)\n${ar} 94: Empress Ogre Hair ×5 **Venena Metacoenubia** (Neo Plastida)\n${ar} 94: Torn Red Cloth ×20 **Sand Bandits Potum** (Geist Desert)\n${ar} 94: Corroded Leather ×30 **Cabrigo** (Ruins of Urban Elban)\n${ar} 95: Spina 300.000\n${ar} 96: Pisteus Bone ×5 **Pisteus** (Ducia Coast: Depths)\n${ar} 96: Phantom Cloth ×20 **Flooray** (Lunagent Cliff Base)\n${ar} 96: Sea Otter Fur ×30 **Lutris** (Ducia Coast: Area 2/3)\n${ar} 97: Arachnidemon Wing ×5 **Arachnidemon** (Arche Valley)\n${ar} 97: Metal Shackles ×20 **Besy** (Arche Valley: Area 1/2/3))\n${ar} 97: Weird Snake Skin ×30 **Coofer** (Rokoko City Ruins)\n${ar} 98: Slimy Hide ×5 **Lord of Nezim** (Nezim Wetlands)\n${ar} 98: Enty Cloth ×20 **Enty** (Witch's Woods: Area 1/2/3)\n${ar} 98: Sturdy Core ×30 **Eerie Scarecrow** (Witch's Woods: Area)\n${ar} 99: Inferno Curse Cloth Scrap ×5 **Hexter** (Witch's Woods)\n${ar} 99: Kappa's Plate ×20 **Kappadon** (Nezim Wetlands)\n${ar} 99: Crow Feather ×30 **Eerie Scarecrow** (Witch's Woods: Area)\n${ar} 100: Wriggling Latevra ×5 **Trocostida** (Nov Diela: Area 1)\n${ar} 100: Viscous Liquid ×20 **Juvestida** (Nov Diela Area 1/2/3)\n${ar} 100: Bizzare Skin ×30 **Evil Eye** (Morga Wasteland: Area 1)`)
        .setImage("https://i.imgur.com/V0UhnF9.png")
        .setTimestamp()
        .setFooter({ text: "Powered by Ancient Luna", iconURL: 'https://i.imgur.com/QZ2gLgq.png' })
        .setColor("#2f3136")

    message.reply({ embeds: [bag1] }).catch((e) => {});
    message.channel.send({ embeds: [bag2, bag3] }).catch((e) => {});
    message.channel.send({ embeds: [bag4, bag5] }).catch((e) => {});
}

module.exports.help = {
    name: 'bag'
}